version: "3.3"
services:
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass